messages:
  goodMorning: '&bДоброе утро!'
  goodAfternoon: '&aДобрый день'
  goodEvening: '&eДобрый вечер'
  goodNight: '&8Приятная ночь, не правда ли?'

options:
  # Message delay in server ticks (1 second = 20 ticks)
  messageDelay: 0
  # 0 = chat
  # 1 = title
  # 2 = actionbar
  messageType: 0
  title:
    fadeIn: 100 # time in milliseconds for titles to fade in.
    stay: 4000 # time in milliseconds for titles to stay.
    fadeOut: 500 # time in milliseconds for titles to fade out.


